/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PronovaPresaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateWhitelist"
      | "bnbToUsdPrice"
      | "bnbUsdPriceFeed"
      | "buyWithBNB"
      | "buyWithETH"
      | "buyWithUSDT"
      | "claimEnabled"
      | "claimTokens"
      | "currentPhase"
      | "emergencyWithdraw"
      | "ethToUsdPrice"
      | "ethUsdPriceFeed"
      | "getCurrentPrices"
      | "getExpectedListingPrice"
      | "getPhaseInfo"
      | "getPresaleProgress"
      | "getReferralInfo"
      | "getUserPurchaseInfo"
      | "getUserRemainingLimit"
      | "lastPurchaseBlock"
      | "maxPurchasePerUser"
      | "owner"
      | "pause"
      | "paused"
      | "phases"
      | "presaleHardCap"
      | "pronovaToken"
      | "referralData"
      | "referralPercentage"
      | "referralRewards"
      | "renounceOwnership"
      | "setChainlinkPriceFeed"
      | "setClaimEnabled"
      | "setWhitelistEnabled"
      | "totalPhases"
      | "totalRaisedUSD"
      | "transferOwnership"
      | "treasuryWallet"
      | "unpause"
      | "updateHardCap"
      | "updatePhase"
      | "updatePrices"
      | "updateUserPurchaseLimit"
      | "updateWhitelist"
      | "usdtToken"
      | "userPurchases"
      | "userTotalPurchased"
      | "whitelist"
      | "whitelistEnabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChainlinkPriceFeedUpdated"
      | "HardCapReached"
      | "OwnershipTransferred"
      | "Paused"
      | "PhaseUpdated"
      | "PriceUpdated"
      | "ReferralRewardEarned"
      | "TokensClaimed"
      | "TokensPurchased"
      | "Unpaused"
      | "UserPurchaseLimitUpdated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateWhitelist",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bnbToUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bnbUsdPriceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithBNB",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithETH",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyWithUSDT",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethToUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ethUsdPriceFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedListingPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPhaseInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPresaleProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPurchaseInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRemainingLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPurchaseBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPurchasePerUser",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "phases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "presaleHardCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pronovaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referralPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkPriceFeed",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPhases",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRaisedUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateHardCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePhase",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrices",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateUserPurchaseLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalPurchased",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistEnabled",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bnbToUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bnbUsdPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyWithBNB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyWithETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyWithUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethToUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethUsdPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedListingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPhaseInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPresaleProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPurchaseInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRemainingLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPurchaseBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPurchasePerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "phases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presaleHardCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pronovaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPhases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRaisedUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateHardCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateUserPurchaseLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistEnabled",
    data: BytesLike
  ): Result;
}

export namespace ChainlinkPriceFeedUpdatedEvent {
  export type InputTuple = [currency: string, priceFeed: AddressLike];
  export type OutputTuple = [currency: string, priceFeed: string];
  export interface OutputObject {
    currency: string;
    priceFeed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HardCapReachedEvent {
  export type InputTuple = [totalRaised: BigNumberish];
  export type OutputTuple = [totalRaised: bigint];
  export interface OutputObject {
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseUpdatedEvent {
  export type InputTuple = [phase: BigNumberish, isActive: boolean];
  export type OutputTuple = [phase: bigint, isActive: boolean];
  export interface OutputObject {
    phase: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [token: string, price: BigNumberish];
  export type OutputTuple = [token: string, price: bigint];
  export interface OutputObject {
    token: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRewardEarnedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    buyer: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [referrer: string, buyer: string, reward: bigint];
  export interface OutputObject {
    referrer: string;
    buyer: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    amount: BigNumberish,
    tokens: BigNumberish,
    phase: BigNumberish,
    paymentMethod: string
  ];
  export type OutputTuple = [
    buyer: string,
    amount: bigint,
    tokens: bigint,
    phase: bigint,
    paymentMethod: string
  ];
  export interface OutputObject {
    buyer: string;
    amount: bigint;
    tokens: bigint;
    phase: bigint;
    paymentMethod: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserPurchaseLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [user: AddressLike, status: boolean];
  export type OutputTuple = [user: string, status: boolean];
  export interface OutputObject {
    user: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PronovaPresale extends BaseContract {
  connect(runner?: ContractRunner | null): PronovaPresale;
  waitForDeployment(): Promise<this>;

  interface: PronovaPresaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateWhitelist: TypedContractMethod<
    [users: AddressLike[], statuses: boolean[]],
    [void],
    "nonpayable"
  >;

  bnbToUsdPrice: TypedContractMethod<[], [bigint], "view">;

  bnbUsdPriceFeed: TypedContractMethod<[], [string], "view">;

  buyWithBNB: TypedContractMethod<[referrer: AddressLike], [void], "payable">;

  buyWithETH: TypedContractMethod<[referrer: AddressLike], [void], "payable">;

  buyWithUSDT: TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  claimEnabled: TypedContractMethod<[], [boolean], "view">;

  claimTokens: TypedContractMethod<[], [void], "nonpayable">;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  ethToUsdPrice: TypedContractMethod<[], [bigint], "view">;

  ethUsdPriceFeed: TypedContractMethod<[], [string], "view">;

  getCurrentPrices: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean, boolean] & {
        ethPrice: bigint;
        bnbPrice: bigint;
        ethChainlinkActive: boolean;
        bnbChainlinkActive: boolean;
      }
    ],
    "view"
  >;

  getExpectedListingPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { minPrice: bigint; maxPrice: bigint }],
    "view"
  >;

  getPhaseInfo: TypedContractMethod<
    [phaseId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        pricePerToken: bigint;
        tokensAllocated: bigint;
        tokensSold: bigint;
        tokensRemaining: bigint;
        isActive: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getPresaleProgress: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalRaised: bigint;
        hardCap: bigint;
        progressPercentage: bigint;
        currentPhaseId: bigint;
      }
    ],
    "view"
  >;

  getReferralInfo: TypedContractMethod<
    [referrer: AddressLike],
    [
      [bigint, bigint, bigint, string[]] & {
        totalReferred: bigint;
        totalRewards: bigint;
        referredCount: bigint;
        referredUsers: string[];
      }
    ],
    "view"
  >;

  getUserPurchaseInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalTokens: bigint;
        totalPaid: bigint;
        referralTokens: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getUserRemainingLimit: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  lastPurchaseBlock: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxPurchasePerUser: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  phases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        pricePerToken: bigint;
        tokensAllocated: bigint;
        tokensSold: bigint;
        minPurchase: bigint;
        maxPurchase: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  presaleHardCap: TypedContractMethod<[], [bigint], "view">;

  pronovaToken: TypedContractMethod<[], [string], "view">;

  referralData: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { totalReferred: bigint; totalRewards: bigint }],
    "view"
  >;

  referralPercentage: TypedContractMethod<[], [bigint], "view">;

  referralRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setChainlinkPriceFeed: TypedContractMethod<
    [currency: string, priceFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  setClaimEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  setWhitelistEnabled: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  totalPhases: TypedContractMethod<[], [bigint], "view">;

  totalRaisedUSD: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryWallet: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateHardCap: TypedContractMethod<
    [_newHardCap: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePhase: TypedContractMethod<
    [phaseId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  updatePrices: TypedContractMethod<
    [_ethPrice: BigNumberish, _bnbPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateUserPurchaseLimit: TypedContractMethod<
    [_newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWhitelist: TypedContractMethod<
    [users: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  userPurchases: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalTokensPurchased: bigint;
        totalAmountPaid: bigint;
        lastPurchaseTime: bigint;
        hasClaimedTokens: boolean;
      }
    ],
    "view"
  >;

  userTotalPurchased: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateWhitelist"
  ): TypedContractMethod<
    [users: AddressLike[], statuses: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bnbToUsdPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bnbUsdPriceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "buyWithBNB"
  ): TypedContractMethod<[referrer: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "buyWithETH"
  ): TypedContractMethod<[referrer: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "buyWithUSDT"
  ): TypedContractMethod<
    [amount: BigNumberish, referrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimTokens"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethToUsdPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ethUsdPriceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrices"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean, boolean] & {
        ethPrice: bigint;
        bnbPrice: bigint;
        ethChainlinkActive: boolean;
        bnbChainlinkActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExpectedListingPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { minPrice: bigint; maxPrice: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPhaseInfo"
  ): TypedContractMethod<
    [phaseId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        pricePerToken: bigint;
        tokensAllocated: bigint;
        tokensSold: bigint;
        tokensRemaining: bigint;
        isActive: boolean;
        startTime: bigint;
        endTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPresaleProgress"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalRaised: bigint;
        hardCap: bigint;
        progressPercentage: bigint;
        currentPhaseId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReferralInfo"
  ): TypedContractMethod<
    [referrer: AddressLike],
    [
      [bigint, bigint, bigint, string[]] & {
        totalReferred: bigint;
        totalRewards: bigint;
        referredCount: bigint;
        referredUsers: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPurchaseInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalTokens: bigint;
        totalPaid: bigint;
        referralTokens: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRemainingLimit"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPurchaseBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPurchasePerUser"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "phases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        pricePerToken: bigint;
        tokensAllocated: bigint;
        tokensSold: bigint;
        minPurchase: bigint;
        maxPurchase: bigint;
        startTime: bigint;
        endTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "presaleHardCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pronovaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralData"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { totalReferred: bigint; totalRewards: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "referralPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChainlinkPriceFeed"
  ): TypedContractMethod<
    [currency: string, priceFeed: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setClaimEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWhitelistEnabled"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPhases"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRaisedUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHardCap"
  ): TypedContractMethod<[_newHardCap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePhase"
  ): TypedContractMethod<
    [phaseId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePrices"
  ): TypedContractMethod<
    [_ethPrice: BigNumberish, _bnbPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateUserPurchaseLimit"
  ): TypedContractMethod<[_newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelist"
  ): TypedContractMethod<
    [users: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        totalTokensPurchased: bigint;
        totalAmountPaid: bigint;
        lastPurchaseTime: bigint;
        hasClaimedTokens: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userTotalPurchased"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "ChainlinkPriceFeedUpdated"
  ): TypedContractEvent<
    ChainlinkPriceFeedUpdatedEvent.InputTuple,
    ChainlinkPriceFeedUpdatedEvent.OutputTuple,
    ChainlinkPriceFeedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HardCapReached"
  ): TypedContractEvent<
    HardCapReachedEvent.InputTuple,
    HardCapReachedEvent.OutputTuple,
    HardCapReachedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseUpdated"
  ): TypedContractEvent<
    PhaseUpdatedEvent.InputTuple,
    PhaseUpdatedEvent.OutputTuple,
    PhaseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRewardEarned"
  ): TypedContractEvent<
    ReferralRewardEarnedEvent.InputTuple,
    ReferralRewardEarnedEvent.OutputTuple,
    ReferralRewardEarnedEvent.OutputObject
  >;
  getEvent(
    key: "TokensClaimed"
  ): TypedContractEvent<
    TokensClaimedEvent.InputTuple,
    TokensClaimedEvent.OutputTuple,
    TokensClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UserPurchaseLimitUpdated"
  ): TypedContractEvent<
    UserPurchaseLimitUpdatedEvent.InputTuple,
    UserPurchaseLimitUpdatedEvent.OutputTuple,
    UserPurchaseLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "ChainlinkPriceFeedUpdated(string,address)": TypedContractEvent<
      ChainlinkPriceFeedUpdatedEvent.InputTuple,
      ChainlinkPriceFeedUpdatedEvent.OutputTuple,
      ChainlinkPriceFeedUpdatedEvent.OutputObject
    >;
    ChainlinkPriceFeedUpdated: TypedContractEvent<
      ChainlinkPriceFeedUpdatedEvent.InputTuple,
      ChainlinkPriceFeedUpdatedEvent.OutputTuple,
      ChainlinkPriceFeedUpdatedEvent.OutputObject
    >;

    "HardCapReached(uint256)": TypedContractEvent<
      HardCapReachedEvent.InputTuple,
      HardCapReachedEvent.OutputTuple,
      HardCapReachedEvent.OutputObject
    >;
    HardCapReached: TypedContractEvent<
      HardCapReachedEvent.InputTuple,
      HardCapReachedEvent.OutputTuple,
      HardCapReachedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PhaseUpdated(uint256,bool)": TypedContractEvent<
      PhaseUpdatedEvent.InputTuple,
      PhaseUpdatedEvent.OutputTuple,
      PhaseUpdatedEvent.OutputObject
    >;
    PhaseUpdated: TypedContractEvent<
      PhaseUpdatedEvent.InputTuple,
      PhaseUpdatedEvent.OutputTuple,
      PhaseUpdatedEvent.OutputObject
    >;

    "PriceUpdated(string,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "ReferralRewardEarned(address,address,uint256)": TypedContractEvent<
      ReferralRewardEarnedEvent.InputTuple,
      ReferralRewardEarnedEvent.OutputTuple,
      ReferralRewardEarnedEvent.OutputObject
    >;
    ReferralRewardEarned: TypedContractEvent<
      ReferralRewardEarnedEvent.InputTuple,
      ReferralRewardEarnedEvent.OutputTuple,
      ReferralRewardEarnedEvent.OutputObject
    >;

    "TokensClaimed(address,uint256)": TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;
    TokensClaimed: TypedContractEvent<
      TokensClaimedEvent.InputTuple,
      TokensClaimedEvent.OutputTuple,
      TokensClaimedEvent.OutputObject
    >;

    "TokensPurchased(address,uint256,uint256,uint256,string)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UserPurchaseLimitUpdated(uint256)": TypedContractEvent<
      UserPurchaseLimitUpdatedEvent.InputTuple,
      UserPurchaseLimitUpdatedEvent.OutputTuple,
      UserPurchaseLimitUpdatedEvent.OutputObject
    >;
    UserPurchaseLimitUpdated: TypedContractEvent<
      UserPurchaseLimitUpdatedEvent.InputTuple,
      UserPurchaseLimitUpdatedEvent.OutputTuple,
      UserPurchaseLimitUpdatedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
