/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PronovaVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "LOCKED_PERCENTAGE"
      | "UNLOCK_INTERVAL"
      | "UNLOCK_PERCENTAGE_PER_INTERVAL"
      | "VESTING_DURATION"
      | "createVestingSchedule"
      | "createWhitepaperVestingSchedule"
      | "getAllSchedules"
      | "getBeneficiaryInfo"
      | "getNextUnlockTime"
      | "getReleasableAmount"
      | "getScheduleDetails"
      | "getTotalReleasableAmount"
      | "getVestingProgress"
      | "getVestingSchedule"
      | "getVestingScheduleCount"
      | "owner"
      | "pronovaToken"
      | "release"
      | "releaseAll"
      | "renounceOwnership"
      | "revoke"
      | "totalReleasedAmount"
      | "totalVestedAmount"
      | "transferOwnership"
      | "vestingSchedules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "TokensReleased"
      | "VestingRevoked"
      | "VestingScheduleCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCKED_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNLOCK_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNLOCK_PERCENTAGE_PER_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VESTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVestingSchedule",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createWhitepaperVestingSchedule",
    values: [AddressLike, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllSchedules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaryInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextUnlockTime",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReleasableAmount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleDetails",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalReleasableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingProgress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingSchedule",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingScheduleCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pronovaToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseAll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReleasedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVestedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingSchedules",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCKED_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNLOCK_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNLOCK_PERCENTAGE_PER_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VESTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createWhitepaperVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllSchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaryInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReleasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReleasableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingScheduleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pronovaToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "releaseAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalReleasedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingSchedules",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingRevokedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    scheduleIndex: BigNumberish
  ];
  export type OutputTuple = [beneficiary: string, scheduleIndex: bigint];
  export interface OutputObject {
    beneficiary: string;
    scheduleIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingScheduleCreatedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    amount: BigNumberish,
    startTime: BigNumberish,
    cliffDuration: BigNumberish,
    vestingDuration: BigNumberish,
    vestingType: BigNumberish
  ];
  export type OutputTuple = [
    beneficiary: string,
    amount: bigint,
    startTime: bigint,
    cliffDuration: bigint,
    vestingDuration: bigint,
    vestingType: bigint
  ];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
    startTime: bigint;
    cliffDuration: bigint;
    vestingDuration: bigint;
    vestingType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PronovaVesting extends BaseContract {
  connect(runner?: ContractRunner | null): PronovaVesting;
  waitForDeployment(): Promise<this>;

  interface: PronovaVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  LOCKED_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  UNLOCK_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  UNLOCK_PERCENTAGE_PER_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  VESTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  createVestingSchedule: TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      revocable: boolean
    ],
    [void],
    "nonpayable"
  >;

  createWhitepaperVestingSchedule: TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      revocable: boolean
    ],
    [void],
    "nonpayable"
  >;

  getAllSchedules: TypedContractMethod<
    [beneficiary: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[]] & {
        totalAmounts: bigint[];
        releasedAmounts: bigint[];
        releasableAmounts: bigint[];
        vestingTypes: bigint[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;

  getBeneficiaryInfo: TypedContractMethod<
    [beneficiary: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalVested: bigint;
        totalReleased: bigint;
        totalReleasable: bigint;
        scheduleCount: bigint;
      }
    ],
    "view"
  >;

  getNextUnlockTime: TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getReleasableAmount: TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getScheduleDetails: TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalAmount: bigint;
        releasedAmount: bigint;
        releasableAmount: bigint;
        nextUnlockTime: bigint;
        progressPercentage: bigint;
        vestingTypeName: string;
      }
    ],
    "view"
  >;

  getTotalReleasableAmount: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  getVestingProgress: TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getVestingSchedule: TypedContractMethod<
    [beneficiary: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        totalAmount: bigint;
        startTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        releasedAmount: bigint;
        revocable: boolean;
        revoked: boolean;
        vestingType: bigint;
      }
    ],
    "view"
  >;

  getVestingScheduleCount: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pronovaToken: TypedContractMethod<[], [string], "view">;

  release: TypedContractMethod<
    [scheduleIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseAll: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revoke: TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalReleasedAmount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalVestedAmount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vestingSchedules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        totalAmount: bigint;
        startTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        releasedAmount: bigint;
        revocable: boolean;
        revoked: boolean;
        vestingType: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCKED_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNLOCK_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNLOCK_PERCENTAGE_PER_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VESTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVestingSchedule"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      revocable: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWhitepaperVestingSchedule"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      amount: BigNumberish,
      startTime: BigNumberish,
      revocable: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllSchedules"
  ): TypedContractMethod<
    [beneficiary: AddressLike],
    [
      [bigint[], bigint[], bigint[], bigint[], boolean[]] & {
        totalAmounts: bigint[];
        releasedAmounts: bigint[];
        releasableAmounts: bigint[];
        vestingTypes: bigint[];
        revokedStatuses: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaryInfo"
  ): TypedContractMethod<
    [beneficiary: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalVested: bigint;
        totalReleased: bigint;
        totalReleasable: bigint;
        scheduleCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextUnlockTime"
  ): TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReleasableAmount"
  ): TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScheduleDetails"
  ): TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalAmount: bigint;
        releasedAmount: bigint;
        releasableAmount: bigint;
        nextUnlockTime: bigint;
        progressPercentage: bigint;
        vestingTypeName: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalReleasableAmount"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVestingProgress"
  ): TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestingSchedule"
  ): TypedContractMethod<
    [beneficiary: AddressLike, index: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        totalAmount: bigint;
        startTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        releasedAmount: bigint;
        revocable: boolean;
        revoked: boolean;
        vestingType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVestingScheduleCount"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pronovaToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[scheduleIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseAll"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [beneficiary: AddressLike, scheduleIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalReleasedAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVestedAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingSchedules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        totalAmount: bigint;
        startTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        releasedAmount: bigint;
        revocable: boolean;
        revoked: boolean;
        vestingType: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VestingRevoked"
  ): TypedContractEvent<
    VestingRevokedEvent.InputTuple,
    VestingRevokedEvent.OutputTuple,
    VestingRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VestingScheduleCreated"
  ): TypedContractEvent<
    VestingScheduleCreatedEvent.InputTuple,
    VestingScheduleCreatedEvent.OutputTuple,
    VestingScheduleCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensReleased(address,uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;

    "VestingRevoked(address,uint256)": TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;
    VestingRevoked: TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;

    "VestingScheduleCreated(address,uint256,uint256,uint256,uint256,uint8)": TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
    VestingScheduleCreated: TypedContractEvent<
      VestingScheduleCreatedEvent.InputTuple,
      VestingScheduleCreatedEvent.OutputTuple,
      VestingScheduleCreatedEvent.OutputObject
    >;
  };
}
