/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PronovaTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIQUIDITY_ALLOCATION"
      | "LOCKED_PERCENTAGE"
      | "MARKETING_ALLOCATION"
      | "PRESALE_ALLOCATION"
      | "STAKING_ALLOCATION"
      | "TEAM_ALLOCATION"
      | "TOTAL_SUPPLY"
      | "TOTAL_VESTING_DURATION"
      | "UNLOCK_INTERVAL"
      | "UNLOCK_PERCENTAGE_PER_INTERVAL"
      | "addTeamMember"
      | "allocationsDistributed"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "burn"
      | "burnFrom"
      | "decimals"
      | "distributeAllocations"
      | "emergencyWithdraw"
      | "getAllocationInfo"
      | "getUnlockableAmount"
      | "isTeamMember"
      | "lastUnlockTime"
      | "liquidityWallet"
      | "lockedBalances"
      | "marketingWallet"
      | "name"
      | "owner"
      | "pause"
      | "paused"
      | "presaleContract"
      | "removeTeamMember"
      | "renounceOwnership"
      | "setLiquidityWallet"
      | "setMarketingWallet"
      | "setPresaleContract"
      | "setStakingContract"
      | "setTeamWallet"
      | "stakingContract"
      | "startVesting"
      | "symbol"
      | "teamMembersCount"
      | "teamWallet"
      | "totalBurned"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "unlockVestedTokens"
      | "unpause"
      | "vestingStartTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllocationsDistributed"
      | "Approval"
      | "LiquidityWalletSet"
      | "MarketingWalletSet"
      | "OwnershipTransferred"
      | "Paused"
      | "PresaleContractSet"
      | "StakingContractSet"
      | "TeamMemberAdded"
      | "TeamMemberRemoved"
      | "TeamWalletSet"
      | "TokensUnlocked"
      | "Transfer"
      | "Unpaused"
      | "VestingStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LIQUIDITY_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCKED_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKETING_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRESALE_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STAKING_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TEAM_ALLOCATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_VESTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNLOCK_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNLOCK_PERCENTAGE_PER_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTeamMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allocationsDistributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "burnFrom",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "distributeAllocations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllocationInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUnlockableAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTeamMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUnlockTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockedBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketingWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "presaleContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeTeamMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLiquidityWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketingWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPresaleContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTeamWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startVesting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "teamMembersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "teamWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockVestedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vestingStartTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "LIQUIDITY_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCKED_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKETING_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRESALE_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STAKING_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TEAM_ALLOCATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_VESTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNLOCK_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNLOCK_PERCENTAGE_PER_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTeamMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocationsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnFrom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeAllocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllocationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnlockableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTeamMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUnlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketingWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presaleContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTeamMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidityWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketingWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPresaleContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTeamWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "teamMembersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teamWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockVestedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vestingStartTime",
    data: BytesLike
  ): Result;
}

export namespace AllocationsDistributedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityWalletSetEvent {
  export type InputTuple = [liquidityWallet: AddressLike];
  export type OutputTuple = [liquidityWallet: string];
  export interface OutputObject {
    liquidityWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketingWalletSetEvent {
  export type InputTuple = [marketingWallet: AddressLike];
  export type OutputTuple = [marketingWallet: string];
  export interface OutputObject {
    marketingWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresaleContractSetEvent {
  export type InputTuple = [presaleContract: AddressLike];
  export type OutputTuple = [presaleContract: string];
  export interface OutputObject {
    presaleContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingContractSetEvent {
  export type InputTuple = [stakingContract: AddressLike];
  export type OutputTuple = [stakingContract: string];
  export interface OutputObject {
    stakingContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeamMemberAddedEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeamMemberRemovedEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeamWalletSetEvent {
  export type InputTuple = [teamWallet: AddressLike];
  export type OutputTuple = [teamWallet: string];
  export interface OutputObject {
    teamWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensUnlockedEvent {
  export type InputTuple = [account: AddressLike, amount: BigNumberish];
  export type OutputTuple = [account: string, amount: bigint];
  export interface OutputObject {
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingStartedEvent {
  export type InputTuple = [startTime: BigNumberish];
  export type OutputTuple = [startTime: bigint];
  export interface OutputObject {
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PronovaToken extends BaseContract {
  connect(runner?: ContractRunner | null): PronovaToken;
  waitForDeployment(): Promise<this>;

  interface: PronovaTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIQUIDITY_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  LOCKED_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  MARKETING_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  PRESALE_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  STAKING_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  TEAM_ALLOCATION: TypedContractMethod<[], [bigint], "view">;

  TOTAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  TOTAL_VESTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  UNLOCK_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  UNLOCK_PERCENTAGE_PER_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  addTeamMember: TypedContractMethod<
    [member: AddressLike],
    [void],
    "nonpayable"
  >;

  allocationsDistributed: TypedContractMethod<[], [boolean], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  burn: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  burnFrom: TypedContractMethod<
    [account: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  distributeAllocations: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getAllocationInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        presaleAlloc: bigint;
        teamAlloc: bigint;
        liquidityAlloc: bigint;
        marketingAlloc: bigint;
        stakingAlloc: bigint;
      }
    ],
    "view"
  >;

  getUnlockableAmount: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  isTeamMember: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastUnlockTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  liquidityWallet: TypedContractMethod<[], [string], "view">;

  lockedBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  marketingWallet: TypedContractMethod<[], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  presaleContract: TypedContractMethod<[], [string], "view">;

  removeTeamMember: TypedContractMethod<
    [member: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setLiquidityWallet: TypedContractMethod<
    [_liquidityWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setMarketingWallet: TypedContractMethod<
    [_marketingWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setPresaleContract: TypedContractMethod<
    [_presaleContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setStakingContract: TypedContractMethod<
    [_stakingContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setTeamWallet: TypedContractMethod<
    [_teamWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingContract: TypedContractMethod<[], [string], "view">;

  startVesting: TypedContractMethod<[], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  teamMembersCount: TypedContractMethod<[], [bigint], "view">;

  teamWallet: TypedContractMethod<[], [string], "view">;

  totalBurned: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unlockVestedTokens: TypedContractMethod<[], [void], "nonpayable">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vestingStartTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIQUIDITY_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCKED_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKETING_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRESALE_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STAKING_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TEAM_ALLOCATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TOTAL_VESTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNLOCK_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UNLOCK_PERCENTAGE_PER_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addTeamMember"
  ): TypedContractMethod<[member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allocationsDistributed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnFrom"
  ): TypedContractMethod<
    [account: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeAllocations"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllocationInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        presaleAlloc: bigint;
        teamAlloc: bigint;
        liquidityAlloc: bigint;
        marketingAlloc: bigint;
        stakingAlloc: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnlockableAmount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTeamMember"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastUnlockTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidityWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lockedBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketingWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "presaleContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTeamMember"
  ): TypedContractMethod<[member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLiquidityWallet"
  ): TypedContractMethod<[_liquidityWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketingWallet"
  ): TypedContractMethod<[_marketingWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPresaleContract"
  ): TypedContractMethod<[_presaleContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingContract"
  ): TypedContractMethod<[_stakingContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTeamWallet"
  ): TypedContractMethod<[_teamWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startVesting"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "teamMembersCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "teamWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBurned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockVestedTokens"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingStartTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AllocationsDistributed"
  ): TypedContractEvent<
    AllocationsDistributedEvent.InputTuple,
    AllocationsDistributedEvent.OutputTuple,
    AllocationsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityWalletSet"
  ): TypedContractEvent<
    LiquidityWalletSetEvent.InputTuple,
    LiquidityWalletSetEvent.OutputTuple,
    LiquidityWalletSetEvent.OutputObject
  >;
  getEvent(
    key: "MarketingWalletSet"
  ): TypedContractEvent<
    MarketingWalletSetEvent.InputTuple,
    MarketingWalletSetEvent.OutputTuple,
    MarketingWalletSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PresaleContractSet"
  ): TypedContractEvent<
    PresaleContractSetEvent.InputTuple,
    PresaleContractSetEvent.OutputTuple,
    PresaleContractSetEvent.OutputObject
  >;
  getEvent(
    key: "StakingContractSet"
  ): TypedContractEvent<
    StakingContractSetEvent.InputTuple,
    StakingContractSetEvent.OutputTuple,
    StakingContractSetEvent.OutputObject
  >;
  getEvent(
    key: "TeamMemberAdded"
  ): TypedContractEvent<
    TeamMemberAddedEvent.InputTuple,
    TeamMemberAddedEvent.OutputTuple,
    TeamMemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "TeamMemberRemoved"
  ): TypedContractEvent<
    TeamMemberRemovedEvent.InputTuple,
    TeamMemberRemovedEvent.OutputTuple,
    TeamMemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TeamWalletSet"
  ): TypedContractEvent<
    TeamWalletSetEvent.InputTuple,
    TeamWalletSetEvent.OutputTuple,
    TeamWalletSetEvent.OutputObject
  >;
  getEvent(
    key: "TokensUnlocked"
  ): TypedContractEvent<
    TokensUnlockedEvent.InputTuple,
    TokensUnlockedEvent.OutputTuple,
    TokensUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VestingStarted"
  ): TypedContractEvent<
    VestingStartedEvent.InputTuple,
    VestingStartedEvent.OutputTuple,
    VestingStartedEvent.OutputObject
  >;

  filters: {
    "AllocationsDistributed()": TypedContractEvent<
      AllocationsDistributedEvent.InputTuple,
      AllocationsDistributedEvent.OutputTuple,
      AllocationsDistributedEvent.OutputObject
    >;
    AllocationsDistributed: TypedContractEvent<
      AllocationsDistributedEvent.InputTuple,
      AllocationsDistributedEvent.OutputTuple,
      AllocationsDistributedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "LiquidityWalletSet(address)": TypedContractEvent<
      LiquidityWalletSetEvent.InputTuple,
      LiquidityWalletSetEvent.OutputTuple,
      LiquidityWalletSetEvent.OutputObject
    >;
    LiquidityWalletSet: TypedContractEvent<
      LiquidityWalletSetEvent.InputTuple,
      LiquidityWalletSetEvent.OutputTuple,
      LiquidityWalletSetEvent.OutputObject
    >;

    "MarketingWalletSet(address)": TypedContractEvent<
      MarketingWalletSetEvent.InputTuple,
      MarketingWalletSetEvent.OutputTuple,
      MarketingWalletSetEvent.OutputObject
    >;
    MarketingWalletSet: TypedContractEvent<
      MarketingWalletSetEvent.InputTuple,
      MarketingWalletSetEvent.OutputTuple,
      MarketingWalletSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PresaleContractSet(address)": TypedContractEvent<
      PresaleContractSetEvent.InputTuple,
      PresaleContractSetEvent.OutputTuple,
      PresaleContractSetEvent.OutputObject
    >;
    PresaleContractSet: TypedContractEvent<
      PresaleContractSetEvent.InputTuple,
      PresaleContractSetEvent.OutputTuple,
      PresaleContractSetEvent.OutputObject
    >;

    "StakingContractSet(address)": TypedContractEvent<
      StakingContractSetEvent.InputTuple,
      StakingContractSetEvent.OutputTuple,
      StakingContractSetEvent.OutputObject
    >;
    StakingContractSet: TypedContractEvent<
      StakingContractSetEvent.InputTuple,
      StakingContractSetEvent.OutputTuple,
      StakingContractSetEvent.OutputObject
    >;

    "TeamMemberAdded(address)": TypedContractEvent<
      TeamMemberAddedEvent.InputTuple,
      TeamMemberAddedEvent.OutputTuple,
      TeamMemberAddedEvent.OutputObject
    >;
    TeamMemberAdded: TypedContractEvent<
      TeamMemberAddedEvent.InputTuple,
      TeamMemberAddedEvent.OutputTuple,
      TeamMemberAddedEvent.OutputObject
    >;

    "TeamMemberRemoved(address)": TypedContractEvent<
      TeamMemberRemovedEvent.InputTuple,
      TeamMemberRemovedEvent.OutputTuple,
      TeamMemberRemovedEvent.OutputObject
    >;
    TeamMemberRemoved: TypedContractEvent<
      TeamMemberRemovedEvent.InputTuple,
      TeamMemberRemovedEvent.OutputTuple,
      TeamMemberRemovedEvent.OutputObject
    >;

    "TeamWalletSet(address)": TypedContractEvent<
      TeamWalletSetEvent.InputTuple,
      TeamWalletSetEvent.OutputTuple,
      TeamWalletSetEvent.OutputObject
    >;
    TeamWalletSet: TypedContractEvent<
      TeamWalletSetEvent.InputTuple,
      TeamWalletSetEvent.OutputTuple,
      TeamWalletSetEvent.OutputObject
    >;

    "TokensUnlocked(address,uint256)": TypedContractEvent<
      TokensUnlockedEvent.InputTuple,
      TokensUnlockedEvent.OutputTuple,
      TokensUnlockedEvent.OutputObject
    >;
    TokensUnlocked: TypedContractEvent<
      TokensUnlockedEvent.InputTuple,
      TokensUnlockedEvent.OutputTuple,
      TokensUnlockedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VestingStarted(uint256)": TypedContractEvent<
      VestingStartedEvent.InputTuple,
      VestingStartedEvent.OutputTuple,
      VestingStartedEvent.OutputObject
    >;
    VestingStarted: TypedContractEvent<
      VestingStartedEvent.InputTuple,
      VestingStartedEvent.OutputTuple,
      VestingStartedEvent.OutputObject
    >;
  };
}
